import catalog from './catalog.json';
import { PREVIEWS } from './previews.generated';

export type Season = 'halloween' | 'christmas';
export type Category = 'costume' | 'pyjamas' | 'sweater' | 'dress' | 'accessory';

export interface Outfit {
  id: string;
  label: string;
  season: Season;
  category: Category;
  /** Flat garment / illustrative placeholder shown on the rack. */
  thumbnail: string;
  /**
   * Photoreal "on a person" result preview. Generated by
   * `scripts/generate-previews.mjs` into /public/outfits/previews/<id>.png and
   * registered in previews.generated.ts. Falls back to `thumbnail` when absent.
   */
  preview?: string;
  /** Description fed to FLUX Kontext for the try-on and for preview generation. */
  prompt: string;
}

export const OUTFITS: Outfit[] = (catalog as Omit<Outfit, 'preview'>[]).map((o) => {
  const preview = PREVIEWS.has(o.id) ? `/outfits/previews/${o.id}.png` : undefined;
  return preview ? { ...o, preview } : o;
});

export function outfitsBySeason(season: Season): Outfit[] {
  return OUTFITS.filter((o) => o.season === season);
}

export function outfitsByCategory(category: Category): Outfit[] {
  return OUTFITS.filter((o) => o.category === category);
}

export function categoriesInSeason(season: Season): Category[] {
  const seen = new Set<Category>();
  for (const o of OUTFITS) {
    if (o.season === season) seen.add(o.category);
  }
  return Array.from(seen);
}
