import catalog from './catalog.json';
import { PREVIEWS } from './previews.generated';

export type Season = 'halloween' | 'christmas';
export type Category =
  | 'costume'
  | 'pyjamas'
  | 'sweater'
  | 'dress'
  | 'suiting'
  | 'outerwear'
  | 'loungewear'
  | 'accessory';

export interface Outfit {
  id: string;
  label: string;
  season: Season;
  category: Category;
  /** Flat garment / illustrative placeholder shown on the rack. */
  thumbnail: string;
  /**
   * Photoreal "on a person" result preview. Generated by
   * `scripts/generate-previews.mjs` into /public/outfits/previews/<id>.png and
   * registered in previews.generated.ts. Falls back to `thumbnail` when absent.
   */
  preview?: string;
  /** Description fed to FLUX Kontext for the try-on and for preview generation. */
  prompt: string;
  /**
   * Optional per-item scene/backdrop. When the "festive scene" option is on,
   * this (or the season default) is sent so the result is restyled into a
   * matching setting instead of keeping the original background.
   */
  scene?: string;
}

/** Default backdrop per season, used when an outfit has no `scene` of its own. */
export const SEASON_SCENES: Record<Season, string> = {
  christmas:
    'a cosy room decorated for Christmas — a decorated tree with warm fairy lights, garland and candles, soft golden bokeh in the background',
  halloween:
    'an atmospheric Halloween setting — dim warm light, carved jack-o-lanterns, cobwebs and flickering candles against a moody dark background'
};

/** The scene description to send for an outfit (per-item override, else season default). */
export function sceneFor(outfit: Pick<Outfit, 'scene' | 'season'>): string {
  return outfit.scene ?? SEASON_SCENES[outfit.season];
}

export const OUTFITS: Outfit[] = (catalog as Omit<Outfit, 'preview'>[]).map((o) => {
  const preview = PREVIEWS.get(o.id);
  return preview ? { ...o, preview } : o;
});

export function outfitsBySeason(season: Season): Outfit[] {
  return OUTFITS.filter((o) => o.season === season);
}

export function outfitsByCategory(category: Category): Outfit[] {
  return OUTFITS.filter((o) => o.category === category);
}

export function categoriesInSeason(season: Season): Category[] {
  const seen = new Set<Category>();
  for (const o of OUTFITS) {
    if (o.season === season) seen.add(o.category);
  }
  return Array.from(seen);
}
