// AUTO-GENERATED by scripts/generate-previews.mjs — do not edit by hand.
// Lists the outfit ids that have a photoreal on-model preview at
// /public/outfits/previews/<id>.png. Regenerate after running the script.

export const PREVIEWS: ReadonlySet<string> = new Set<string>([
  // (no previews generated yet — run `npm run previews`)
]);
