// AUTO-GENERATED by scripts/generate-previews.mjs — do not edit by hand.
// Maps an outfit id to its photoreal on-model preview under /public/outfits/previews/.
// (Hand-added entries are fine too; regenerate to re-scan the folder.)

export const PREVIEWS: ReadonlyMap<string, string> = new Map<string, string>([
  ["black-velvet-jumpsuit", "/outfits/previews/black-velvet-jumpsuit.jpg"],
  ["black-wool-overcoat", "/outfits/previews/black-wool-overcoat.jpg"],
  ["burgundy-snowflake-coat", "/outfits/previews/burgundy-snowflake-coat.jpg"],
  ["burgundy-velvet-gown", "/outfits/previews/burgundy-velvet-gown.jpg"],
  ["cream-sweater-dress", "/outfits/previews/cream-sweater-dress.jpg"],
  ["crimson-baroque-gown", "/outfits/previews/crimson-baroque-gown.jpg"],
  ["emerald-velvet-gown", "/outfits/previews/emerald-velvet-gown.jpg"],
  ["gold-fringe-jumpsuit", "/outfits/previews/gold-fringe-jumpsuit.jpg"],
  ["green-cable-knit", "/outfits/previews/green-cable-knit.jpg"],
  ["green-sequin-skirt-set", "/outfits/previews/green-sequin-skirt-set.jpg"],
  ["green-velvet-blazer", "/outfits/previews/green-velvet-blazer.jpg"],
  ["green-velvet-dress", "/outfits/previews/green-velvet-dress.jpg"],
  ["green-velvet-halter-gown", "/outfits/previews/green-velvet-halter-gown.jpg"],
  ["green-velvet-tuxedo", "/outfits/previews/green-velvet-tuxedo.jpg"],
  ["lace-snowflake-catsuit", "/outfits/previews/lace-snowflake-catsuit.jpg"],
  ["mrs-claus", "/outfits/previews/mrs-claus.jpg"],
  ["pj-fairisle", "/outfits/previews/pj-fairisle.jpg"],
  ["pj-green-satin", "/outfits/previews/pj-green-satin.jpg"],
  ["pj-red-plaid", "/outfits/previews/pj-red-plaid.jpg"],
  ["plaid-flannel-shirt", "/outfits/previews/plaid-flannel-shirt.jpg"],
  ["puffer-jacket", "/outfits/previews/puffer-jacket.jpg"],
  ["red-sequin-slip-dress", "/outfits/previews/red-sequin-slip-dress.jpg"],
  ["silver-cutout-midi", "/outfits/previews/silver-cutout-midi.jpg"],
  ["silver-statement-jacket", "/outfits/previews/silver-statement-jacket.jpg"],
  ["sweater", "/outfits/previews/sweater.jpg"],
  ["tartan-wool-coat", "/outfits/previews/tartan-wool-coat.jpg"],
  ["velvet-robe", "/outfits/previews/velvet-robe.jpg"]
]);
