// AUTO-GENERATED by scripts/generate-previews.mjs — do not edit by hand.
// Maps an outfit id to its photoreal on-model preview under /public/outfits/previews/.
// (Hand-added entries are fine too; regenerate to re-scan the folder.)

export const PREVIEWS: ReadonlyMap<string, string> = new Map<string, string>([
  ['black-velvet-jumpsuit', '/outfits/previews/black-velvet-jumpsuit.jpg'],
  ['cream-sweater-dress', '/outfits/previews/cream-sweater-dress.jpg'],
  ['crimson-baroque-gown', '/outfits/previews/crimson-baroque-gown.jpg'],
  ['emerald-velvet-gown', '/outfits/previews/emerald-velvet-gown.jpg'],
  ['green-velvet-blazer', '/outfits/previews/green-velvet-blazer.jpg'],
  ['green-velvet-dress', '/outfits/previews/green-velvet-dress.jpg'],
  ['mrs-claus', '/outfits/previews/mrs-claus.jpg'],
  ['red-sequin-slip-dress', '/outfits/previews/red-sequin-slip-dress.jpg']
]);
